Repository TheSynergyTEAM/cucumberclient, pull requests merged in 2021-03, with the labels that each got.

#2 개발환경 세팅
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
  yarn.lock
Labels: ⚙env

#3 route 설정
  src/App.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/index.ts
  src/pages/index.tsx
Labels: 🚗feature

#5 각 파일 초기 값 설정 및 절대 경로 참조 추가
  src/api/index.ts
  src/components/index.ts
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  tsconfig.json
Labels: ⚙env

#7 theme provider 및 글로벌 스타일 설정
  src/App.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: 🌼style, 🚗feature

#8 header 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/pages/index.tsx
Labels: 🌈design, 🌼style, 🚗feature

#11 반응형 컨테이너 컴포넌트 추가 및 헤더 스타일 수정
  .eslintrc.js
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/common/Container/index.tsx
  src/pages/Create.tsx
  src/pages/index.tsx
Labels: 🌈design

#16 회원가입 페이지 UI
  .eslintrc.js
  .gitignore
  package-lock.json
  src/components/Header/style.ts
  src/components/auth/SignUpContainer/index.tsx
  src/components/auth/SignUpContainer/style.ts
  src/components/auth/SignUpForm/index.tsx
  src/components/auth/SignUpForm/style.ts
  src/components/auth/SignUpSide/index.tsx
  src/components/auth/SignUpSide/style.ts
  src/components/auth/SignUpStep/index.tsx
  src/components/auth/SignUpStep/style.ts
  src/components/common/Container/index.tsx
  src/context/SignUp.ts
  src/pages/SignUp.tsx
  src/pages/index.tsx
  src/styles/breakpoints.ts
  src/styles/colors.json
  src/styles/index.ts
  src/styles/theme.ts
Labels: UI

#17 로그인 UI 구성
  package-lock.json
  package.json
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/SignIn/index.tsx
  src/components/SignIn/style.ts
  src/styles/colors.json
  src/styles/global.less
  src/styles/index.ts
  src/styles/theme.ts
Labels: UI, 🌼style

#19 마이페이지 UI 구성
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/common/ArticleBox/index.tsx
  src/components/common/ArticleBox/style.ts
  src/components/myInfo/EditProfile/index.tsx
  src/components/myInfo/EditProfile/style.ts
  src/components/myInfo/Like/index.tsx
  src/components/myInfo/Like/style.ts
  src/components/myInfo/ListBox/index.tsx
  src/components/myInfo/ListBox/style.ts
  src/components/myInfo/ProfileBox/index.tsx
  src/components/myInfo/ProfileBox/style.ts
  src/components/myInfo/Trade/index.tsx
  src/components/myInfo/Trade/style.ts
  src/context/SignIn.ts
  src/pages/MyInfo.tsx
  src/pages/index.tsx
  src/styles/index.ts
  src/type.d.ts
Labels: UI, 🌼style, 🚗feature

#20 채팅방 UI
  .eslintrc.js
  package-lock.json
  src/components/Header/index.tsx
  src/components/chat/Container/index.tsx
  src/components/chat/Container/style.ts
  src/components/chat/Header/index.tsx
  src/components/chat/Header/style.ts
  src/components/chat/contents/ChatList/index.tsx
  src/components/chat/contents/ChatList/style.ts
  src/components/chat/contents/Main/index.tsx
  src/components/chat/contents/Main/style.ts
  src/components/chat/contents/UserInfo/index.tsx
  src/components/chat/contents/UserInfo/style.ts
  src/components/chat/hooks/chat.ts
  src/components/chat/hooks/column-size.ts
  src/components/common/Container/index.tsx
  src/pages/Chat.tsx
  src/pages/index.tsx
  src/styles/colors.json
  src/styles/index.ts
  src/styles/theme.ts
Labels: UI

#21 feat: provide redirects file for netlify spa
  public/_redirects
Labels: ⚙env
