Repository TheSynergyTEAM/cucumberclient, pull requests merged in 2021-04, with the labels that each got.

#22 회원가입 > 유저 주소 API 정의 및 연결
  package-lock.json
  package.json
  src/api/address/index.ts
  src/api/auth/index.ts
  src/components/auth/SignUpForm/index.tsx
  src/components/auth/SignUpForm/style.ts
  src/components/auth/SignUpStep/index.tsx
  src/components/auth/SignUpStep/style.ts
  src/components/auth/hooks/address.ts
  src/components/chat/contents/ChatList/style.ts
  src/components/index.ts
  src/index.tsx
  src/styles/index.ts
  src/type.d.ts
  src/types/address.d.ts
  src/utils/axios.ts
Labels: UI, ⚙env, 🚗feature

#23 detail page
  package-lock.json
  src/components/common/ArticleBox/index.tsx
  src/components/detail/DetailInfo/index.tsx
  src/components/detail/DetailInfo/style.ts
  src/components/detail/ImgBox/index.tsx
  src/components/detail/ImgBox/style.ts
  src/pages/Detail.tsx
  src/pages/index.tsx
  src/type.d.ts
  tsconfig.json
Labels: UI, 🌈design, 🌼style

#24 README.md 업데이트
  README.md
Labels: 📃documentation

#26 type 설정 방식 변경
  src/api/address/index.ts
  src/components/Header/index.tsx
  src/components/auth/hooks/address.ts
  src/components/common/ArticleBox/index.tsx
  src/components/detail/DetailInfo/index.tsx
  src/components/myInfo/Like/index.tsx
  src/components/myInfo/Trade/index.tsx
  src/pages/Detail.tsx
  src/pages/MyInfo.tsx
  src/types/address.d.ts
  src/types/article.d.ts
  src/types/index.d.ts
  src/types/user.d.ts
  tsconfig.json
Labels: ⚙env

#27 회원 인증 관련 초안
  src/App.tsx
  src/api/auth/index.ts
  src/components/Header/index.tsx
  src/components/SignIn/index.tsx
  src/components/auth/SignUpForm/index.tsx
  src/context/user.ts
  src/types/user.d.ts
  src/utils/axios.ts
Labels: 🚗feature

#29 feat: RequiredLogin 컴포넌트 추가
  src/components/auth/RequiredLogin/index.tsx
  src/pages/Chat.tsx
Labels: 🚗feature
